"""
Sabaq - Voice Teaching Assistant

Two ways in:

- Upload a finished recording, transcribed in one batch request. The
  language is forced to Urdu by default: left to detect it, the batch model
  heard three of four speakers as Hindi, wrote Devanagari, kept 16% of
  technical terms in English and dropped the densest sentences. Forced to
  Urdu, the same audio kept 79% and lost none of them.
- Stream over a WebSocket, correcting each turn as it lands. The published
  evaluation uses whisper-rt, which reports the detected language per turn.
  In the deployed app, the browser microphone records a 16 kHz WAV first and
  then feeds that recording through the same streaming path; a direct hardware
  microphone remains available when Sabaq is run locally.

Either way you get:

1. A corrected transcript, with technical terms restored to English
2. A summary, key points, and practice questions
3. The Urdu vocabulary the glossary did not cover, so it can grow from
   measurements instead of guesses
4. A comparison across lectures, to show where the glossary holds and fails

Notes are generated by Gemini where possible and by Groq when Gemini is out
of quota. Model selection inside each provider is automatic, discovered with
a listing call that costs no generation quota. The sidebar can pin one
provider, which is how the two are compared on the same transcript.

Only the raw transcript is held in session state. Correction is re-run on
every render, so the fuzzy matching toggle changes the result immediately
and costs no API call.

Run:
    streamlit run app.py
"""

import logging
import os
import tempfile
import time

import assemblyai as aai
import streamlit as st

from config import get_key, mask
from live import (
    WHISPER_RT,
    LiveTranscriber,
    ffmpeg_available,
    file_chunks,
    microphone_available,
    microphone_chunks,
    transcribe_recording,
)
from speak import speak
from normalizer import (
    GENERAL_TERMS, clean_transcript, has_devanagari, unknown_terms,
)
from subject_glossaries import SUBJECTS
from runs import build_run, load_runs, save_run, summary_rows, term_matrix, to_csv
from teacher import (
    GEMINI, GROQ, TERM_STYLES, active_backend, answer_question,
    provider_status, study_notes,
)

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("sabaq")

MAX_MB = 25
ALLOWED = ["mp3", "wav", "m4a", "mp4"]
NOTE_KEYS = ("summary", "points", "questions", "backend", "answer", "speak_pending")

# Labels for a saved run. Not the glossary list: that is SUBJECTS, imported
# from subject_glossaries. Reusing the name here once replaced the imported
# list, so the sidebar offered "AI / ML" and "Other" as glossaries and every
# transcript failed with KeyError: 'AI / ML'.
RUN_SUBJECTS = ["AI / ML", "Database", "Web development",
                "Software engineering", "Cloud computing", "Cybersecurity",
                "Operating systems", "Other"]

# Batch language. Forced Urdu is the default because it was measured better:
# 79% of technical terms in English on the new speakers against 16% with
# detection, two runs per lecture, identical (README, evaluation finding 8). Detection
# stays available because it was the evaluated default until then, and on
# one S1 lecture it did slightly better. whisper-rt, the live path, rejects
# a language parameter, so this choice exists only for uploads.
BATCH_LANGUAGES = {
    "Urdu": "ur",
    "Detect automatically": None,
}

PROVIDER_CHOICES = {
    "Automatic": None,
    "Gemini only": GEMINI,
    "Groq only": GROQ,
}


# -----------------------------
# Page setup
# -----------------------------

st.set_page_config(page_title="Sabaq", page_icon="🎓", layout="wide")

st.title("Sabaq 🎓")
st.caption("AI lecture assistant for classrooms that mix Urdu and English")


# -----------------------------
# API keys
# -----------------------------

aai_key = get_key("ASSEMBLYAI_API_KEY")

# One dict, keyed the way teacher.py expects, so adding a provider later is
# a config change rather than a signature change.
keys = {
    GEMINI: get_key("GEMINI_API_KEY"),
    GROQ: get_key("GROQ_API_KEY"),
}

if not aai_key:
    st.error(
        "No AssemblyAI API key found.\n\n"
        "Local: add ASSEMBLYAI_API_KEY to your .env file\n\n"
        "Deployed: add it in the app's Secrets settings"
    )
    st.stop()

aai.settings.api_key = aai_key


# -----------------------------
# Sidebar
# -----------------------------

st.sidebar.caption(f"Speech key: {mask(aai_key)}")
st.sidebar.caption(
    f"Gemini key: {mask(keys[GEMINI]) if keys[GEMINI] else 'not set'}"
)
st.sidebar.caption(
    f"Groq key: {mask(keys[GROQ]) if keys[GROQ] else 'not set'}"
)

st.sidebar.divider()

provider_label = st.sidebar.radio(
    "Note generator",
    list(PROVIDER_CHOICES.keys()),
    help=(
        "Automatic uses Gemini first, then falls back to Groq. Pin one to "
        "compare how each handles a code-switched transcript."
    ),
)
force_provider = PROVIDER_CHOICES[provider_label]

if any(keys.values()):
    backend = active_backend(keys, force_provider)
    if backend:
        provider, model = backend
        st.sidebar.success(f"{provider}: {model}")
    else:
        st.sidebar.warning("No note generator reachable right now")

    # Per provider, not just the winner. A key that is set but unusable is
    # the failure that looks like success, so it gets said out loud.
    with st.sidebar.expander("Provider status"):
        for row in provider_status(keys):
            if row["ready"]:
                st.write(f"✅ {row['provider']}: {row['detail']}")
            else:
                st.write(f"⚠️ {row['provider']}: {row['detail']}")

st.sidebar.divider()

subjects = tuple(st.sidebar.multiselect(
    "Subject glossaries",
    list(SUBJECTS),
    default=list(SUBJECTS),
    help=(
        "AI / ML terms are always corrected. These starter glossaries add a "
        "few core terms per subject, each spelling observed in real "
        "recordings, in Urdu script and Devanagari."
    ),
))

use_fuzzy = st.sidebar.checkbox(
    "Fuzzy matching for unseen spellings",
    value=False,
    help="Off by default. It corrupts short Urdu words. Turn on to see that failure.",
)

notes_language = st.sidebar.radio("Notes language", ["English", "Urdu"])

term_style = st.sidebar.selectbox(
    "Technical terms",
    list(TERM_STYLES.keys()),
    help="How English technical terms should appear in the notes.",
)


# -----------------------------
# Transcription
# -----------------------------

def remove_temp(path: str | None) -> None:
    """
    Delete a temporary audio file without ever failing the page.

    On Windows a file another process still holds cannot be deleted
    (WinError 32), and ffmpeg can take a moment to let go after it is
    stopped. A failed handshake raised exactly that and took the whole page
    down. Retry briefly, then leave the file to the system's temp cleanup.
    """
    if not path:
        return
    for _ in range(10):
        try:
            os.remove(path)
            return
        except FileNotFoundError:
            return
        except PermissionError:
            time.sleep(0.2)
    log.warning("could not delete temporary file %s; left for the system", path)


def connection_hint(error: str) -> str:
    """The streaming error, with what to do about the one users actually hit."""
    if "handshake" in error.lower() or "connection failed" in error.lower():
        return (
            "Could not reach the streaming service in time (the connection "
            f"handshake failed). Try again. Details: {error}"
        )
    return error

def transcribe(file, language: str | None = "ur") -> tuple[str, int | None]:
    """
    Send an uploaded file to AssemblyAI. Returns (text, duration_seconds).

    language is a language code to force, or None to let the API detect it.
    The same two settings as the evaluation's batch_ur and batch paths.
    """
    audio_path = None

    try:
        suffix = os.path.splitext(file.name)[1]

        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            tmp.write(file.getbuffer())
            audio_path = tmp.name

        config = (
            aai.TranscriptionConfig(language_code=language)
            if language
            else aai.TranscriptionConfig(language_detection=True)
        )
        result = aai.Transcriber().transcribe(audio_path, config=config)

        if result.status == aai.TranscriptStatus.error:
            log.error("AssemblyAI returned an error status for %s", file.name)
            return "", None

        return result.text or "", result.audio_duration

    finally:
        remove_temp(audio_path)


# -----------------------------
# Note generation
# -----------------------------

def generate_notes(transcript: str) -> None:
    """
    One request per set of notes, across whichever provider answers.

    The reply shape is enforced by a schema, so a parse failure is a real
    failure and not a reason to spend three more requests on separate calls.
    """
    with st.spinner("Generating study notes..."):
        notes = study_notes(
            keys, transcript, notes_language, term_style, force=force_provider
        )

    if not notes.get("summary"):
        st.error("The model's reply could not be read. Try generating again.")
        return

    st.session_state["summary"] = notes["summary"]
    st.session_state["points"] = notes["points"]
    st.session_state["questions"] = notes["questions"]
    st.session_state["backend"] = notes.get("backend", "")


# -----------------------------
# Live streaming
# -----------------------------

def accept_transcript(
    raw: str, duration: int | None, turns: list[dict], path: str
) -> None:
    """Hand a finished transcript to the rest of the app, whichever path made it."""
    st.session_state["raw"] = raw
    st.session_state["duration"] = duration
    st.session_state["turns"] = turns
    # Batch or live. Saved with a run, since the two paths give very
    # different results on the same audio and a comparison must say which.
    st.session_state["path"] = path

    # Clear old notes so they never belong to a previous recording.
    for stale in NOTE_KEYS:
        st.session_state.pop(stale, None)


def turn_line(turn: dict) -> str:
    """One finished turn, corrected, with the language the API reported."""
    corrected, _ = clean_transcript(turn["text"], use_fuzzy=use_fuzzy, subjects=subjects)

    tag = ""
    if turn.get("language"):
        confidence = turn.get("confidence")
        score = f" {confidence:.2f}" if isinstance(confidence, float) else ""
        tag = f"`{turn['language']}{score}` "

    return f"{tag}{corrected}"


def lag_text(lag: float | None) -> str:
    """The measured lag, or an honest 'unknown' when turns carry no timestamps."""
    if lag is None:
        return "lag unknown (no word timestamps)"
    return f"median lag {lag:.1f}s"


def run_live(chunks, source: str) -> None:
    """
    Stream audio, correcting each turn as it arrives.

    Drawing happens here, on the main thread, from a snapshot the SDK's read
    thread only appends to. Correction is re-run per turn rather than at the
    end, because a term appearing in English while the teacher is still on
    the slide is the whole point of the live path.
    """
    session = LiveTranscriber(aai_key, speech_model=WHISPER_RT)

    status = st.empty()
    live_box = st.empty()
    started = time.monotonic()
    last_drawn = [0.0]

    def draw() -> None:
        # Four redraws a second. Every chunk would spend the whole session
        # rendering instead of sending audio.
        now = time.monotonic()
        if now - last_drawn[0] < 0.25:
            return
        last_drawn[0] = now

        turns, partial, error = session.snapshot()

        phase = {
            "draining": "audio finished, collecting the last turn",
            "closing": "closing the session",
            "done": "finished",
        }.get(session.phase, "listening")
        status.caption(
            f"{source} · {WHISPER_RT} · {now - started:.0f}s · "
            f"{len(turns)} turns · {phase} · {lag_text(session.lag())}"
        )

        lines = [turn_line(turn) for turn in turns]
        if partial:
            lines.append(f"_{partial}_")
        live_box.markdown("\n\n".join(lines) or "_Listening..._")

        if error:
            status.error(connection_hint(error))

    try:
        raw = session.run(chunks, on_update=draw)
    except Exception:
        log.exception("Live streaming failed")
        st.error("The live session failed. Check the sidebar key and try again.")
        return

    turns, _, error = session.snapshot()

    if error:
        st.error(connection_hint(error))

    # Whatever the server said about the session. Silence here means the
    # missing audio is not something it chose to warn about.
    #
    # getattr, not session.notices: a finished 90 second stream is too
    # expensive to lose to an AttributeError from a half-updated checkout.
    for notice in getattr(session, "notices", []):
        st.warning(f"Server notice: {notice}")

    # The one silent failure seen in evaluation: a session that stopped after
    # its first turn with no error. If the server also stopped receiving
    # audio, its own count says so.
    unheard = session.unheard_audio_sec()
    if unheard:
        st.warning(
            f"The server reports receiving {session.server_audio_sec:.0f}s of "
            f"the {session.audio_sent():.0f}s of audio sent. The last "
            f"{unheard:.0f}s were never heard, so the transcript ends early. "
            "Stream it again."
        )

    if not raw.strip():
        st.warning("No speech was transcribed. Check the input level and try again.")
        return

    accept_transcript(raw, int(time.monotonic() - started), turns, "live")
    st.success(
        f"Live transcript ready: {len(turns)} turns, {lag_text(session.lag())}"
    )


# -----------------------------
# Input
# -----------------------------

mode = st.radio(
    "Transcribe",
    ["Upload a recording", "Stream it live"],
    horizontal=True,
    help=(
        "Upload sends the finished file in one batch request. Stream opens a "
        "WebSocket and corrects each turn as it lands."
    ),
)

if mode == "Upload a recording":
    batch_choice = st.radio(
        "Lecture language",
        list(BATCH_LANGUAGES),
        horizontal=True,
        help=(
            "Urdu is forced by default. Left to detect the language, the "
            "speech model heard three of four test speakers as Hindi and "
            "kept 16% of technical terms in English; forced to Urdu it kept "
            "79% and did not drop sentences. Measured on two runs per lecture."
        ),
    )
    batch_language = BATCH_LANGUAGES[batch_choice]

    uploaded = st.file_uploader(
        f"Upload a lecture recording (max {MAX_MB} MB)", type=ALLOWED
    )

    if uploaded:
        size_mb = uploaded.size / (1024 * 1024)

        if size_mb > MAX_MB:
            st.error(f"That file is {size_mb:.1f} MB. Keep it under {MAX_MB} MB.")
            st.stop()

        st.audio(uploaded)

        if st.button("Transcribe", type="primary"):
            try:
                with st.spinner("Transcribing. Roughly a third of the audio length."):
                    raw, duration = transcribe(uploaded, batch_language)

                if not raw:
                    st.warning("No speech detected, or transcription failed.")
                    st.stop()

                accept_transcript(
                    raw, duration, [], "batch_ur" if batch_language else "batch"
                )
                st.success("Transcript ready")

            except Exception:
                # Log it, but never surface the raw exception: some SDKs
                # include the key in the message.
                log.exception("Transcription failed")
                st.error("Transcription failed. Try again.")

else:
    # A direct Python/sounddevice microphone reads the machine running the
    # Streamlit server. That works locally, but Streamlit Community Cloud has
    # no physical input device. st.audio_input, by contrast, records from the
    # visitor's browser microphone and therefore works in the deployed app.
    mic_ok, mic_reason = microphone_available()

    st.caption(
        f"Streaming model: `{WHISPER_RT}`. This is the streaming model used for "
        "Sabaq's published evaluation. Language is detected per turn, so a "
        "switch mid-lecture is labelled as it happens."
    )

    sources = [
        "Browser microphone (record, then stream)",
        "Play a file through the stream",
    ]
    if mic_ok:
        sources.insert(1, "Direct microphone (local only)")

    source = st.radio("Audio source", sources, horizontal=True)

    if not mic_ok:
        st.caption(
            "Browser microphone works in the hosted app. A direct hardware "
            "microphone is shown only when Sabaq runs on a machine with an "
            "input device."
        )
        if mic_reason:
            log.info("direct microphone unavailable: %s", mic_reason)

    if source == "Browser microphone (record, then stream)":
        st.caption(
            "Record in the browser, then Sabaq sends the 16 kHz WAV through "
            "the same AssemblyAI streaming path used by the live evaluation. "
            "The transcript still arrives turn by turn while the recording is "
            "replayed at real speed."
        )

        browser_recording = st.audio_input(
            "Record a lecture",
            sample_rate=16_000,
            key="live_browser_audio",
        )

        if browser_recording:
            st.audio(browser_recording)

            if st.button("Stream browser recording", type="primary"):
                browser_path = None
                try:
                    with tempfile.NamedTemporaryFile(
                        delete=False, suffix=".wav"
                    ) as tmp:
                        tmp.write(browser_recording.getbuffer())
                        browser_path = tmp.name

                    run_live(
                        file_chunks(browser_path),
                        "browser microphone",
                    )
                finally:
                    remove_temp(browser_path)

    elif source == "Direct microphone (local only)":
        seconds = st.slider("Listen for (seconds)", 15, 300, 60, step=15)
        st.caption(
            "This is true direct microphone streaming from the machine running "
            "Python. It is available locally when an input device is present."
        )

        if st.button("Start listening", type="primary"):
            run_live(microphone_chunks(seconds), "direct microphone")

    else:
        streamed = st.file_uploader(
            "Recording to play through the live stream",
            type=ALLOWED,
            key="stream_upload",
        )

        if not ffmpeg_available():
            st.info(
                "ffmpeg is not installed, so only a 16 kHz mono wav can be "
                "streamed. Install ffmpeg to stream mp3, m4a or mp4."
            )

        if streamed:
            st.audio(streamed)
            st.caption(
                "Played at recording speed, not read at disk speed, so turn "
                "detection behaves the way it would on a live microphone. "
                "This takes as long as the recording."
            )

            if st.button("Start streaming", type="primary"):
                suffix = os.path.splitext(streamed.name)[1]
                with tempfile.NamedTemporaryFile(
                    delete=False, suffix=suffix
                ) as tmp:
                    tmp.write(streamed.getbuffer())
                    stream_path = tmp.name

                try:
                    run_live(file_chunks(stream_path), streamed.name)
                finally:
                    remove_temp(stream_path)


# -----------------------------
# Results
# -----------------------------

if "raw" in st.session_state:
    raw = st.session_state["raw"]

    # Recomputed every render, so the fuzzy toggle is live and free.
    corrected, changes = clean_transcript(raw, use_fuzzy=use_fuzzy, subjects=subjects)
    leftovers = unknown_terms(corrected)
    # Technical and everyday words counted apart, so "students" and
    # "lecture" do not inflate the number that matters.
    everyday_fixed = sum(
        c["times"] for c in changes if c["replaced_with"] in GENERAL_TERMS
    )
    technical_fixed = sum(c["times"] for c in changes) - everyday_fixed

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Words", len(raw.split()))
    col2.metric("Technical terms corrected", technical_fixed)
    col3.metric("Everyday words corrected", everyday_fixed)
    if st.session_state.get("duration"):
        col4.metric("Length", f"{st.session_state['duration']} sec")

    turns = st.session_state.get("turns") or []
    languages = {}
    for turn in turns:
        if turn.get("language"):
            languages[turn["language"]] = languages.get(turn["language"], 0) + 1

    if len(languages) > 1:
        spread = ", ".join(f"{code} ×{count}" for code, count in languages.items())
        st.warning(
            f"The speech API reported more than one language in this recording "
            f"({spread}). Spoken Urdu and Hindi are close enough that the model "
            "often cannot tell them apart, so a 'hi' turn usually marks the "
            "switch to Devanagari script, caught as it happened rather than "
            "found afterwards."
        )
    elif languages:
        st.caption(
            "Detected language: "
            + ", ".join(f"{code} ({count} turns)" for code, count in languages.items())
        )

    if has_devanagari(raw):
        st.warning(
            "Part of this transcript is in Devanagari script. Only Devanagari "
            "spellings already observed are in the glossary, so most of that "
            "section is left uncorrected. See the Not covered tab."
        )

    (tab_notes, tab_ask, tab_transcript, tab_changes, tab_unknown,
     tab_compare) = st.tabs(
        ["Study notes", "Ask the lecture", "Transcript", "Corrections",
         "Not covered", "Compare lectures"]
    )

    # --- Transcript ---
    with tab_transcript:
        left, right = st.columns(2)

        with left:
            st.subheader("Raw")
            st.caption("Straight from the speech API")
            st.write(raw)

        with right:
            st.subheader("Corrected")
            st.caption("Technical terms restored to English")
            st.write(corrected)

        if turns:
            st.divider()
            st.subheader("Turn by turn")
            st.caption(
                "What the live session produced, one turn at a time, with the "
                "language the API reported for each."
            )
            st.dataframe(
                [
                    {
                        "#": turn["order"],
                        "Language": turn.get("language") or "",
                        "Confidence": turn.get("confidence") or "",
                        "Audio at": turn.get("audio_at", ""),
                        "Arrived": turn.get("received_at", ""),
                        "Lag (s)": turn.get("lag") if turn.get("lag") is not None else "",
                        "Corrected": clean_transcript(
                            turn["text"], use_fuzzy=use_fuzzy,
                            subjects=subjects,
                        )[0],
                    }
                    for turn in turns
                ],
                width="stretch",
                hide_index=True,
            )

        down1, down2 = st.columns(2)
        down1.download_button(
            "Download raw", data=raw,
            file_name="transcript_raw.txt", mime="text/plain",
        )
        down2.download_button(
            "Download corrected", data=corrected,
            file_name="transcript_corrected.txt", mime="text/plain",
        )

    # --- Corrections ---
    with tab_changes:
        if changes:
            st.caption("Every spelling the normalizer replaced, and how often.")
            st.dataframe(changes, width="stretch", hide_index=True)
        else:
            st.info("No known technical terms found in this transcript.")

        st.divider()
        st.caption("Save this run to compare it against other lectures.")

        name_col, subject_col, save_col = st.columns([2, 2, 1])
        label = name_col.text_input("Lecture name", placeholder="Overfitting")
        subject = subject_col.selectbox("Subject", RUN_SUBJECTS)

        if save_col.button("Save run", disabled=not label):
            run = build_run(
                label, subject, raw, corrected, changes,
                st.session_state.get("duration"), leftovers,
                settings={
                    "path": st.session_state.get("path", ""),
                    "glossaries": list(subjects),
                    "fuzzy": use_fuzzy,
                },
            )
            st.session_state.setdefault("session_runs", []).append(run)

            if save_run(run):
                st.success(f"Saved to runs/ as {label}")
            else:
                st.success(f"Saved for this session as {label}")
                st.caption("Disk is read only here, so this run lasts until reload.")

    # --- Not covered ---
    with tab_unknown:
        st.caption(
            "Urdu words still standing after correction, most frequent first. "
            "Most are ordinary Urdu. The rest are transliterated technical "
            "terms the glossary has not met yet, and they are how it grows."
        )

        if leftovers:
            st.dataframe(leftovers, width="stretch", hide_index=True)
            st.download_button(
                "Download uncovered terms",
                data="\n".join(f"{row['term']}\t{row['times']}" for row in leftovers),
                file_name="uncovered_terms.txt",
                mime="text/plain",
            )
        else:
            st.info("Nothing left over.")

    # --- Comparison ---
    with tab_compare:
        saved = load_runs()
        seen = {r["label"] for r in saved}
        saved += [
            r for r in st.session_state.get("session_runs", [])
            if r["label"] not in seen
        ]

        if len(saved) < 2:
            st.info(
                "Save at least two runs to compare them. Transcribe another "
                "lecture, then save it from the corrections tab."
            )
        else:
            st.subheader("Per lecture")
            st.dataframe(summary_rows(saved), width="stretch",
                         hide_index=True)
            st.caption(
                "Corrections per 100 words shows how term-heavy a lecture is. "
                "Unique terms shows how much of the glossary it exercised."
            )

            st.subheader("Which terms appeared where")
            st.caption(
                "Blank cells on a new subject mean the glossary does not cover "
                "that vocabulary yet."
            )
            st.dataframe(term_matrix(saved), width="stretch",
                         hide_index=True)

            st.download_button(
                "Download comparison as CSV",
                data=to_csv(saved),
                file_name="sabaq_lecture_comparison.csv",
                mime="text/csv",
            )

    # --- Study notes ---
    with tab_notes:
        if not any(keys.values()):
            st.warning(
                "Add GEMINI_API_KEY or GROQ_API_KEY to generate study notes."
            )
        else:
            if st.button("Generate study notes"):
                try:
                    generate_notes(corrected)
                except Exception:
                    log.exception("Note generation failed")
                    st.error(
                        "Could not generate notes. Every provider may be rate "
                        "limited. Try again shortly, or switch provider in the "
                        "sidebar."
                    )

            if st.session_state.get("backend"):
                st.caption(f"Generated by {st.session_state['backend']}")

            if st.session_state.get("summary"):
                st.subheader("Summary")
                st.write(st.session_state["summary"])

            if st.session_state.get("points"):
                st.subheader("Key points")
                for point in st.session_state["points"]:
                    st.markdown(f"- {point}")

            if st.session_state.get("questions"):
                st.subheader("Practice questions")
                for number, item in enumerate(st.session_state["questions"], start=1):
                    with st.expander(f"{number}. {item['question']}"):
                        st.write(item["answer"])
    # --- Ask the lecture ---
    with tab_ask:
        st.caption(
            "Ask by voice or in writing. The answer comes from this "
            "transcript only, and the app says when the teacher did not "
            "cover what you asked."
        )

        if not any(keys.values()):
            st.warning(
                "Add GEMINI_API_KEY or GROQ_API_KEY to ask questions."
            )
        else:
            spoken = st.audio_input("Record your question")
            typed = st.text_input(
                "Or type it",
                placeholder="Overfitting kya hoti hai?",
            )

            if st.button("Ask", type="primary", disabled=not (spoken or typed)):
                question = typed.strip()
                heard_by_voice = False

                if question:
                    # A typed question in Urdu script needs the same
                    # correction as a spoken one, or آور فٹنگ never meets
                    # "overfitting" in the transcript.
                    question, _ = clean_transcript(
                        question, use_fuzzy=use_fuzzy, subjects=subjects
                    )

                if spoken and not question:
                    heard_by_voice = True
                    question_path = None
                    try:
                        with tempfile.NamedTemporaryFile(
                            delete=False, suffix=".wav"
                        ) as tmp:
                            tmp.write(spoken.getbuffer())
                            question_path = tmp.name

                        with st.spinner("Listening to your question..."):
                            heard, _ = transcribe_recording(aai_key, question_path)

                        # The question goes through the same normalizer as the
                        # lecture. A question about آور فٹنگ and a transcript
                        # about overfitting are otherwise different words.
                        question, _ = clean_transcript(heard, use_fuzzy=use_fuzzy, subjects=subjects)

                    except Exception:
                        log.exception("Question transcription failed")
                        st.error("Could not transcribe the question. Try typing it.")
                        question = ""
                    finally:
                        remove_temp(question_path)

                if question:
                    try:
                        with st.spinner("Reading the transcript..."):
                            reply = answer_question(
                                keys, corrected, question,
                                notes_language, term_style,
                                force=force_provider,
                            )
                    except Exception:
                        log.exception("Answering failed")
                        st.error(
                            "Could not answer. Every provider may be rate "
                            "limited. Try again shortly."
                        )
                        reply = {}

                    if reply.get("answer"):
                        reply["question"] = question
                        reply["by_voice"] = heard_by_voice
                        # The language it was written in, so a later change
                        # in the sidebar does not read it with the wrong voice.
                        reply["language"] = notes_language
                        st.session_state["answer"] = reply
                        # Spoken once, when it arrives. The tab is redrawn on
                        # every interaction, and autoplay on each redraw
                        # would read the answer again.
                        st.session_state["speak_pending"] = True
                    elif reply:
                        st.error("The model's reply could not be read. Ask again.")

            reply = st.session_state.get("answer")

            if reply:
                st.divider()
                prefix = "Heard" if reply.get("by_voice") else "Asked"
                st.caption(f"{prefix}: {reply['question']}")

                if reply["in_lecture"]:
                    st.success("Answered from the lecture")
                else:
                    st.warning(
                        "The teacher did not cover this. Nothing below is "
                        "from the lecture."
                    )

                st.write(reply["answer"])
                speak(
                    reply["answer"],
                    reply.get("language", notes_language),
                    autoplay=st.session_state.pop("speak_pending", False),
                )

                if reply.get("basis"):
                    with st.expander("Where this came from in the transcript"):
                        st.write(reply["basis"])

                if reply.get("backend"):
                    st.caption(f"Generated by {reply['backend']}")