"""
Sabaq - Voice Teaching Assistant

Two ways in:

- Upload a finished recording, transcribed in one batch request.
- Stream live over a WebSocket, correcting each turn as it lands. Live uses
  whisper-rt, the only streaming model that supports Urdu, and it reports the
  detected language per turn, which is how the Urdu to Devanagari flip becomes
  visible while it is happening instead of afterwards.

Either way you get:

1. A corrected transcript, with technical terms restored to English
2. A summary, key points, and practice questions
3. The Urdu vocabulary the glossary did not cover, so it can grow from
   measurements instead of guesses
4. A comparison across lectures, to show where the glossary holds and fails

Notes are generated by Gemini where possible and by Groq when Gemini is out
of quota. Model selection inside each provider is automatic, discovered with
a listing call that costs no generation quota. The sidebar can pin one
provider, which is how the two are compared on the same transcript.

Only the raw transcript is held in session state. Correction is re-run on
every render, so the fuzzy matching toggle changes the result immediately
and costs no API call.

Run:
    streamlit run app.py
"""

import logging
import os
import tempfile
import time

import assemblyai as aai
import streamlit as st

from config import get_key, mask
from live import (
    WHISPER_RT,
    LiveTranscriber,
    ffmpeg_available,
    file_chunks,
    microphone_available,
    microphone_chunks,
    transcribe_recording,
)
from speak import speak
from normalizer import clean_transcript, has_devanagari, unknown_terms
from runs import build_run, load_runs, save_run, summary_rows, term_matrix, to_csv
from teacher import (
    GEMINI, GROQ, TERM_STYLES, active_backend, answer_question,
    provider_status, study_notes,
)

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("sabaq")

MAX_MB = 25
ALLOWED = ["mp3", "wav", "m4a", "mp4"]
NOTE_KEYS = ("summary", "points", "questions", "backend", "answer")
SUBJECTS = ["AI / ML", "Database", "Web development", "Other"]

PROVIDER_CHOICES = {
    "Automatic": None,
    "Gemini only": GEMINI,
    "Groq only": GROQ,
}


# -----------------------------
# Page setup
# -----------------------------

st.set_page_config(page_title="Sabaq", page_icon="🎓", layout="wide")

st.title("Sabaq 🎓")
st.caption("AI lecture assistant for classrooms that mix Urdu and English")


# -----------------------------
# API keys
# -----------------------------

aai_key = get_key("ASSEMBLYAI_API_KEY")

# One dict, keyed the way teacher.py expects, so adding a provider later is
# a config change rather than a signature change.
keys = {
    GEMINI: get_key("GEMINI_API_KEY"),
    GROQ: get_key("GROQ_API_KEY"),
}

if not aai_key:
    st.error(
        "No AssemblyAI API key found.\n\n"
        "Local: add ASSEMBLYAI_API_KEY to your .env file\n\n"
        "Deployed: add it in the app's Secrets settings"
    )
    st.stop()

aai.settings.api_key = aai_key


# -----------------------------
# Sidebar
# -----------------------------

st.sidebar.caption(f"Speech key: {mask(aai_key)}")
st.sidebar.caption(
    f"Gemini key: {mask(keys[GEMINI]) if keys[GEMINI] else 'not set'}"
)
st.sidebar.caption(
    f"Groq key: {mask(keys[GROQ]) if keys[GROQ] else 'not set'}"
)

st.sidebar.divider()

provider_label = st.sidebar.radio(
    "Note generator",
    list(PROVIDER_CHOICES.keys()),
    help=(
        "Automatic uses Gemini first, then falls back to Groq. Pin one to "
        "compare how each handles a code-switched transcript."
    ),
)
force_provider = PROVIDER_CHOICES[provider_label]

if any(keys.values()):
    backend = active_backend(keys, force_provider)
    if backend:
        provider, model = backend
        st.sidebar.success(f"{provider}: {model}")
    else:
        st.sidebar.warning("No note generator reachable right now")

    # Per provider, not just the winner. A key that is set but unusable is
    # the failure that looks like success, so it gets said out loud.
    with st.sidebar.expander("Provider status"):
        for row in provider_status(keys):
            if row["ready"]:
                st.write(f"✅ {row['provider']}: {row['detail']}")
            else:
                st.write(f"⚠️ {row['provider']}: {row['detail']}")

st.sidebar.divider()

use_fuzzy = st.sidebar.checkbox(
    "Fuzzy matching for unseen spellings",
    value=False,
    help="Off by default. It corrupts short Urdu words. Turn on to see that failure.",
)

notes_language = st.sidebar.radio("Notes language", ["English", "Urdu"])

term_style = st.sidebar.selectbox(
    "Technical terms",
    list(TERM_STYLES.keys()),
    help="How English technical terms should appear in the notes.",
)


# -----------------------------
# Transcription
# -----------------------------

def transcribe(file) -> tuple[str, int | None]:
    """Send an uploaded file to AssemblyAI. Returns (text, duration_seconds)."""
    audio_path = None

    try:
        suffix = os.path.splitext(file.name)[1]

        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as tmp:
            tmp.write(file.getbuffer())
            audio_path = tmp.name

        config = aai.TranscriptionConfig(language_detection=True)
        result = aai.Transcriber().transcribe(audio_path, config=config)

        if result.status == aai.TranscriptStatus.error:
            log.error("AssemblyAI returned an error status for %s", file.name)
            return "", None

        return result.text or "", result.audio_duration

    finally:
        if audio_path and os.path.exists(audio_path):
            os.remove(audio_path)


# -----------------------------
# Note generation
# -----------------------------

def generate_notes(transcript: str) -> None:
    """
    One request per set of notes, across whichever provider answers.

    The reply shape is enforced by a schema, so a parse failure is a real
    failure and not a reason to spend three more requests on separate calls.
    """
    with st.spinner("Generating study notes..."):
        notes = study_notes(
            keys, transcript, notes_language, term_style, force=force_provider
        )

    if not notes.get("summary"):
        st.error("The model's reply could not be read. Try generating again.")
        return

    st.session_state["summary"] = notes["summary"]
    st.session_state["points"] = notes["points"]
    st.session_state["questions"] = notes["questions"]
    st.session_state["backend"] = notes.get("backend", "")


# -----------------------------
# Live streaming
# -----------------------------

def accept_transcript(raw: str, duration: int | None, turns: list[dict]) -> None:
    """Hand a finished transcript to the rest of the app, whichever path made it."""
    st.session_state["raw"] = raw
    st.session_state["duration"] = duration
    st.session_state["turns"] = turns

    # Clear old notes so they never belong to a previous recording.
    for stale in NOTE_KEYS:
        st.session_state.pop(stale, None)


def turn_line(turn: dict) -> str:
    """One finished turn, corrected, with the language the API reported."""
    corrected, _ = clean_transcript(turn["text"], use_fuzzy=use_fuzzy)

    tag = ""
    if turn.get("language"):
        confidence = turn.get("confidence")
        score = f" {confidence:.2f}" if isinstance(confidence, float) else ""
        tag = f"`{turn['language']}{score}` "

    return f"{tag}{corrected}"


def run_live(chunks, source: str) -> None:
    """
    Stream audio, correcting each turn as it arrives.

    Drawing happens here, on the main thread, from a snapshot the SDK's read
    thread only appends to. Correction is re-run per turn rather than at the
    end, because a term appearing in English while the teacher is still on
    the slide is the whole point of the live path.
    """
    session = LiveTranscriber(aai_key, speech_model=WHISPER_RT)

    status = st.empty()
    live_box = st.empty()
    started = time.monotonic()
    last_drawn = [0.0]

    def draw() -> None:
        # Four redraws a second. Every chunk would spend the whole session
        # rendering instead of sending audio.
        now = time.monotonic()
        if now - last_drawn[0] < 0.25:
            return
        last_drawn[0] = now

        turns, partial, error = session.snapshot()

        phase = (
            "waiting for the tail — whisper-rt runs behind the audio"
            if session.phase == "draining"
            else "listening"
        )
        status.caption(
            f"{source} · {WHISPER_RT} · {now - started:.0f}s · "
            f"{len(turns)} turns · {phase} · {session.lag():.0f}s behind"
        )

        lines = [turn_line(turn) for turn in turns]
        if partial:
            lines.append(f"_{partial}_")
        live_box.markdown("\n\n".join(lines) or "_Listening..._")

        if error:
            status.error(error)

    try:
        raw = session.run(chunks, on_update=draw)
    except Exception:
        log.exception("Live streaming failed")
        st.error("The live session failed. Check the sidebar key and try again.")
        return

    turns, _, error = session.snapshot()

    if error:
        st.error(error)

    # Whatever the server said about the session. Silence here means the
    # missing audio is not something it chose to warn about.
    #
    # getattr, not session.notices: a finished 90 second stream is too
    # expensive to lose to an AttributeError from a half-updated checkout.
    for notice in getattr(session, "notices", []):
        st.warning(f"Server notice: {notice}")

    if not raw.strip():
        st.warning("No speech was transcribed. Check the input level and try again.")
        return

    accept_transcript(raw, int(time.monotonic() - started), turns)
    st.success(
        f"Live transcript ready: {len(turns)} turns, "
        f"last one {session.lag():.0f}s behind the audio"
    )


# -----------------------------
# Input
# -----------------------------

mode = st.radio(
    "Transcribe",
    ["Upload a recording", "Stream it live"],
    horizontal=True,
    help=(
        "Upload sends the finished file in one batch request. Stream opens a "
        "WebSocket and corrects each turn as it lands."
    ),
)

if mode == "Upload a recording":
    uploaded = st.file_uploader(
        f"Upload a lecture recording (max {MAX_MB} MB)", type=ALLOWED
    )

    if uploaded:
        size_mb = uploaded.size / (1024 * 1024)

        if size_mb > MAX_MB:
            st.error(f"That file is {size_mb:.1f} MB. Keep it under {MAX_MB} MB.")
            st.stop()

        st.audio(uploaded)

        if st.button("Transcribe", type="primary"):
            try:
                with st.spinner("Transcribing. Roughly a third of the audio length."):
                    raw, duration = transcribe(uploaded)

                if not raw:
                    st.warning("No speech detected, or transcription failed.")
                    st.stop()

                accept_transcript(raw, duration, [])
                st.success("Transcript ready")

            except Exception:
                # Log it, but never surface the raw exception: some SDKs
                # include the key in the message.
                log.exception("Transcription failed")
                st.error("Transcription failed. Try again.")

else:
    mic_ok, mic_reason = microphone_available()

    sources = ["Play a file through the stream"]
    if mic_ok:
        sources.insert(0, "Microphone")

    st.caption(
        f"Streaming model: `{WHISPER_RT}`. The other two streaming models cover "
        "six European languages and cannot hear Urdu at all. Language is "
        "detected per turn, so a switch mid-lecture is labelled as it happens."
    )

    source = st.radio("Audio source", sources, horizontal=True)

    if not mic_ok:
        st.info(f"Microphone unavailable here: {mic_reason}. Streaming a file instead.")

    if source == "Microphone":
        seconds = st.slider("Listen for (seconds)", 15, 300, 60, step=15)
        st.caption(
            "Capped on purpose. Streaming is billed on how long the socket "
            "stays open, and an abandoned session bills for three hours."
        )

        if st.button("Start listening", type="primary"):
            run_live(microphone_chunks(seconds), "microphone")

    else:
        streamed = st.file_uploader(
            "Recording to play through the live stream", type=ALLOWED,
            key="stream_upload",
        )

        if not ffmpeg_available():
            st.info(
                "ffmpeg is not installed, so only a 16 kHz mono wav can be "
                "streamed. Install ffmpeg to stream mp3, m4a or mp4."
            )

        if streamed:
            st.audio(streamed)
            st.caption(
                "Played at recording speed, not read at disk speed, so turn "
                "detection behaves the way it would on a live microphone. "
                "This takes as long as the recording."
            )

            if st.button("Start streaming", type="primary"):
                suffix = os.path.splitext(streamed.name)[1]
                with tempfile.NamedTemporaryFile(
                    delete=False, suffix=suffix
                ) as tmp:
                    tmp.write(streamed.getbuffer())
                    stream_path = tmp.name

                try:
                    run_live(file_chunks(stream_path), streamed.name)
                finally:
                    if os.path.exists(stream_path):
                        os.remove(stream_path)


# -----------------------------
# Results
# -----------------------------

if "raw" in st.session_state:
    raw = st.session_state["raw"]

    # Recomputed every render, so the fuzzy toggle is live and free.
    corrected, changes = clean_transcript(raw, use_fuzzy=use_fuzzy)
    leftovers = unknown_terms(corrected)
    total_fixed = sum(c["times"] for c in changes)

    col1, col2, col3 = st.columns(3)
    col1.metric("Words", len(raw.split()))
    col2.metric("Terms corrected", total_fixed)
    if st.session_state.get("duration"):
        col3.metric("Length", f"{st.session_state['duration']} sec")

    turns = st.session_state.get("turns") or []
    languages = {}
    for turn in turns:
        if turn.get("language"):
            languages[turn["language"]] = languages.get(turn["language"], 0) + 1

    if len(languages) > 1:
        spread = ", ".join(f"{code} ×{count}" for code, count in languages.items())
        st.warning(
            f"The speech API reported more than one language in this recording "
            f"({spread}). Urdu and Hindi are the same language in two scripts, "
            "so a 'hi' turn is the script flip, caught as it happened rather "
            "than found afterwards."
        )
    elif languages:
        st.caption(
            "Detected language: "
            + ", ".join(f"{code} ({count} turns)" for code, count in languages.items())
        )

    if has_devanagari(raw):
        st.warning(
            "Part of this transcript is in Devanagari script. Every glossary "
            "variant is in Urdu script, so that section cannot be corrected."
        )

    (tab_notes, tab_ask, tab_transcript, tab_changes, tab_unknown,
     tab_compare) = st.tabs(
        ["Study notes", "Ask the lecture", "Transcript", "Corrections",
         "Not covered", "Compare lectures"]
    )

    # --- Transcript ---
    with tab_transcript:
        left, right = st.columns(2)

        with left:
            st.subheader("Raw")
            st.caption("Straight from the speech API")
            st.write(raw)

        with right:
            st.subheader("Corrected")
            st.caption("Technical terms restored to English")
            st.write(corrected)

        if turns:
            st.divider()
            st.subheader("Turn by turn")
            st.caption(
                "What the live session produced, one turn at a time, with the "
                "language the API reported for each."
            )
            st.dataframe(
                [
                    {
                        "#": turn["order"],
                        "Language": turn.get("language") or "",
                        "Confidence": turn.get("confidence") or "",
                        "Audio at": turn.get("audio_at", ""),
                        "Arrived": turn.get("received_at", ""),
                        "Corrected": clean_transcript(
                            turn["text"], use_fuzzy=use_fuzzy
                        )[0],
                    }
                    for turn in turns
                ],
                use_container_width=True,
                hide_index=True,
            )

        down1, down2 = st.columns(2)
        down1.download_button(
            "Download raw", data=raw,
            file_name="transcript_raw.txt", mime="text/plain",
        )
        down2.download_button(
            "Download corrected", data=corrected,
            file_name="transcript_corrected.txt", mime="text/plain",
        )

    # --- Corrections ---
    with tab_changes:
        if changes:
            st.caption("Every spelling the normalizer replaced, and how often.")
            st.dataframe(changes, use_container_width=True, hide_index=True)
        else:
            st.info("No known technical terms found in this transcript.")

        st.divider()
        st.caption("Save this run to compare it against other lectures.")

        name_col, subject_col, save_col = st.columns([2, 2, 1])
        label = name_col.text_input("Lecture name", placeholder="Overfitting")
        subject = subject_col.selectbox("Subject", SUBJECTS)

        if save_col.button("Save run", disabled=not label):
            run = build_run(
                label, subject, raw, corrected, changes,
                st.session_state.get("duration"), leftovers,
            )
            st.session_state.setdefault("session_runs", []).append(run)

            if save_run(run):
                st.success(f"Saved to runs/ as {label}")
            else:
                st.success(f"Saved for this session as {label}")
                st.caption("Disk is read only here, so this run lasts until reload.")

    # --- Not covered ---
    with tab_unknown:
        st.caption(
            "Urdu words still standing after correction, most frequent first. "
            "Most are ordinary Urdu. The rest are transliterated technical "
            "terms the glossary has not met yet, and they are how it grows."
        )

        if leftovers:
            st.dataframe(leftovers, use_container_width=True, hide_index=True)
            st.download_button(
                "Download uncovered terms",
                data="\n".join(f"{row['term']}\t{row['times']}" for row in leftovers),
                file_name="uncovered_terms.txt",
                mime="text/plain",
            )
        else:
            st.info("Nothing left over.")

    # --- Comparison ---
    with tab_compare:
        saved = load_runs()
        seen = {r["label"] for r in saved}
        saved += [
            r for r in st.session_state.get("session_runs", [])
            if r["label"] not in seen
        ]

        if len(saved) < 2:
            st.info(
                "Save at least two runs to compare them. Transcribe another "
                "lecture, then save it from the corrections tab."
            )
        else:
            st.subheader("Per lecture")
            st.dataframe(summary_rows(saved), use_container_width=True,
                         hide_index=True)
            st.caption(
                "Corrections per 100 words shows how term-heavy a lecture is. "
                "Unique terms shows how much of the glossary it exercised."
            )

            st.subheader("Which terms appeared where")
            st.caption(
                "Blank cells on a new subject mean the glossary does not cover "
                "that vocabulary yet."
            )
            st.dataframe(term_matrix(saved), use_container_width=True,
                         hide_index=True)

            st.download_button(
                "Download comparison as CSV",
                data=to_csv(saved),
                file_name="sabaq_lecture_comparison.csv",
                mime="text/csv",
            )

    # --- Study notes ---
    with tab_notes:
        if not any(keys.values()):
            st.warning(
                "Add GEMINI_API_KEY or GROQ_API_KEY to generate study notes."
            )
        else:
            if st.button("Generate study notes"):
                try:
                    generate_notes(corrected)
                except Exception:
                    log.exception("Note generation failed")
                    st.error(
                        "Could not generate notes. Every provider may be rate "
                        "limited. Try again shortly, or switch provider in the "
                        "sidebar."
                    )

            if st.session_state.get("backend"):
                st.caption(f"Generated by {st.session_state['backend']}")

            if st.session_state.get("summary"):
                st.subheader("Summary")
                st.write(st.session_state["summary"])

            if st.session_state.get("points"):
                st.subheader("Key points")
                for point in st.session_state["points"]:
                    st.markdown(f"- {point}")

            if st.session_state.get("questions"):
                st.subheader("Practice questions")
                for number, item in enumerate(st.session_state["questions"], start=1):
                    with st.expander(f"{number}. {item['question']}"):
                        st.write(item["answer"])
    # --- Ask the lecture ---
    with tab_ask:
        st.caption(
            "Ask by voice or in writing. The answer comes from this "
            "transcript only, and the app says when the teacher did not "
            "cover what you asked."
        )

        if not any(keys.values()):
            st.warning(
                "Add GEMINI_API_KEY or GROQ_API_KEY to ask questions."
            )
        else:
            spoken = st.audio_input("Record your question")
            typed = st.text_input(
                "Or type it",
                placeholder="Overfitting kya hoti hai?",
            )

            if st.button("Ask", type="primary", disabled=not (spoken or typed)):
                question = typed.strip()

                if spoken and not question:
                    question_path = None
                    try:
                        with tempfile.NamedTemporaryFile(
                            delete=False, suffix=".wav"
                        ) as tmp:
                            tmp.write(spoken.getbuffer())
                            question_path = tmp.name

                        with st.spinner("Listening to your question..."):
                            heard, _ = transcribe_recording(aai_key, question_path)

                        # The question goes through the same normalizer as the
                        # lecture. A question about آور فٹنگ and a transcript
                        # about overfitting are otherwise different words.
                        question, _ = clean_transcript(heard, use_fuzzy=use_fuzzy)

                    except Exception:
                        log.exception("Question transcription failed")
                        st.error("Could not transcribe the question. Try typing it.")
                        question = ""
                    finally:
                        if question_path and os.path.exists(question_path):
                            os.remove(question_path)

                if question:
                    try:
                        with st.spinner("Reading the transcript..."):
                            reply = answer_question(
                                keys, corrected, question,
                                notes_language, term_style,
                                force=force_provider,
                            )
                    except Exception:
                        log.exception("Answering failed")
                        st.error(
                            "Could not answer. Every provider may be rate "
                            "limited. Try again shortly."
                        )
                        reply = {}

                    if reply.get("answer"):
                        reply["question"] = question
                        st.session_state["answer"] = reply
                    elif reply:
                        st.error("The model's reply could not be read. Ask again.")

            reply = st.session_state.get("answer")

            if reply:
                st.divider()
                st.caption(f"Heard: {reply['question']}")

                if reply["in_lecture"]:
                    st.success("Answered from the lecture")
                else:
                    st.warning(
                        "The teacher did not cover this. Nothing below is "
                        "from the lecture."
                    )

                st.write(reply["answer"])
                speak(reply["answer"], notes_language)

                if reply.get("basis"):
                    with st.expander("Where this came from in the transcript"):
                        st.write(reply["basis"])

                if reply.get("backend"):
                    st.caption(f"Generated by {reply['backend']}")